version: '3.8'  # Puedes usar la versión que prefieras

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:ollama
    ports:
      - "3000:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: always

volumes:
  ollama:
  open-webui:
